CREATE DATABASE nmusic;

USE nmusic;

CREATE TABLE usuario (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nome VARCHAR(30) NOT NULL,
	email VARCHAR(30) NOT NULL UNIQUE,
	sobrenome VARCHAR(30) NOT NULL,
	senha VARCHAR(100) NOT NULL,
	tipo CHAR(3) NOT NULL
);